services:
  mysql:
    image: mysql:8.0
    container_name: siia_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: siia_db
      MYSQL_USER: siia_user
      MYSQL_PASSWORD: siia_pass
    ports:
      - "3399:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - siia_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

  app:
    build: .
    container_name: siia_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/siia_db?useSSL=false&serverTimezone=America/Santiago&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: siia_user
      SPRING_DATASOURCE_PASSWORD: siia_pass
      JWT_SECRET: MiClaveSecretaSuperSeguraParaJWT2026!
    networks:
      - siia_network

volumes:
  mysql_data:

networks:
  siia_network:
    driver: bridge